### ISSUE TITLE
[RELEASE] v1.0 of Argilla LlamaIndex Integration

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla-llama-index#16]
- [x] Code rebase
- [x] Pinning LlamaIndex to v0.10
- [x] Adapt test suite
- [ ] Argilla tutorial using the integration

**Comment by alvarobartt** [comment]
Hi here! Also note that `llama-index` pins `argilla` to `>= 1.22.0` in their current codebase, so we should do the same within this package 🤝 

See https://github.com/run-llama/llama_index/blob/0ae69d46e3735a740214c22a5f72e05d46d92635/llama-index-integrations/callbacks/llama-index-callbacks-argilla/pyproject.toml#L35
