### ISSUE TITLE
ValueError: Eval mode argilla not supported.

### ISSUE THREAD

**Issue by andysingal** [argilla-io/argilla-llama-index#5]
<img width="744" alt="Screenshot 2024-01-23 at 8 56 34 PM" src="https://github.com/argilla-io/argilla-llama-index/assets/20493493/d6bf6841-02a1-4ec4-ab0b-71ade495fc23">

**Comment by davidberenstein1957** [comment]
Hello @andysingal , this is still WIP and should be integrated through a PR with llama-index or manually changing their set_global_handler method.

**Comment by andysingal** [comment]
> Hello @andysingal , this is still WIP and should be integrated through a PR with llama-index or manually changing their set_global_handler method.

Awesome, looking forward to it

**Comment by kursathalat** [comment]
Hey @andysingal, for a simple workaround for now, you can go to this [Pull Request](https://github.com/run-llama/llama_index/pull/10214/files), download the 2 files there and copy-paste them to your local llama-index/callbacks folder. Then, please install the packaga via `pip install argilla-llama-index`, and then you shoud be fine to go for now. Until the work is merged, this should work.
